import localFont from "next/font/local";
import "./globals.css";
import UseRouter from "./components/UseRouter";
import ServerComponent from "./components/ServerComponent";
import LearnCss from "./components/LearnCss";
import DataFetch from "./components/DataFetch";
import LikePhp from "./components/LikePhp";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LikePhp/>
        {/* <DataFetch/> */}
        {/* <LearnCss/> */}
        {/* <ServerComponent/> */}
        {/* <UseRouter/> */}
        {children}
      </body>
    </html>
  );
}
